### PR TITLE
fix(intercom): fix date conversion from unix timestamp to js date of intercom attributes

### LINKED ISSUE #640: Intercom: dates are all in 1970
## Expected behavior

Dates shown in "Intercom attributes" are expected to be correct.

## Actual behavior

Dates look exactly like in your screenshot at https://docs.forestadmin.com/documentation/reference-guide/integrations#intercom - they're all in 1970.

Dates returned by the Intercom integration are returned as a Unix time, e.g.`1613415151`.
The Date constructor in JS is expecting a number of milliseconds since Unix epoch, e.g. `1613415151000`
```
> new Date(1613415151)
1970-01-19T16:10:15.151Z
```

## Context

* intercom-client: 2.11.0, used with Intercom API 2.0
* forest-express: 7.9.6
* express: 4.17.1

### PR DESCRIPTION
**Pull request by jeffladiray**
Close #640

## Pull Request checklist:

- [x] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [x] Test manually the implemented changes
- [x] Review my own code (indentation, syntax, style, simplicity, readability)
- [x] Wonder if you can improve the existing code

### CODE REVIEW

File: src/integrations/intercom/serializers/intercom-attributes.js [hunk 1]
```diff
@@ -3,6 +3,17 @@ const JSONAPISerializer = require('jsonapi-serializer').Serializer;
...
+    unixTimestamp && new Date(unixTimestamp * 1000);
+
+  // Attributes keys ending with `_at` are unix timestamp
+  // thus they need to be converted to js Date
+  Object.entries(attributes).forEach(([attributeKey, attributeValue]) => {
+    if (attributeKey.endsWith('_at')) {
+      attributes[attributeKey] = unixTimestampToDateOrNull(attributeValue);
+    }
+  });
+
```
Comment (GuillaumeCisco) [inline src/integrations/intercom/serializers/intercom-attributes.js:16]: No need to use `new Date(...)`, as only the timestamp can do the job.
Works well this way :)

**Review by GuillaumeCisco — APPROVED** [review]
Tested! 🏁 
Works great! 🎉

File: src/integrations/intercom/serializers/intercom-attributes.js (hunk 1 above)
Comment (jeffladiray) [reply src/integrations/intercom/serializers/intercom-attributes.js:16]: I agree, but looking at other dates sent by the agents, it seems like they are sent as `new Date()` instead of timestamp, so I'll keep it this way for consistency
